### ISSUE TITLE
Where to enter the coordinates?

### ISSUE THREAD

**Issue by akammerer** [InfotelGLPI/positions#63]
* Version of the plugin : 6.0.1
* Version of your GLPI : 10.0.2
* Steps to reproduce (which actions have you made) :
I installed the cartogaphie plugin, double checked the url matching the global settings, uploaded jpg pictures to files/_plugins/positions/pics and assigned them to computer/workstation and monitor/24". I can see them in the Assignment section of the config. I Uploaded a Document with the gif of a Map. If I open tools/cartographie, select the location and click "see map" the map shows fine. But I have no clue where/how to enter the coordinates for a Item so that it shows up in the map? If I select "Computer" and "DemoPC" in the "create coordinates section I get "No location selected". If I click on "Save the coordinates" first and select "computer/DemoPC" then, clicking "Add" does not throw any error, but also no thing changes on the map. 
If I open "Assets/Computer/DemoPC" and select "Cartographies" I see a Name and the location and I can click on "Post" there, but nothing happens after that.
* Expected result : I would like to see my DemoPC on the map
* Actual result : The map shows, but nothing more
* URL of the page : http://cmdb.and.at/glpi (not reachable from extern)

Do you have any hint for me where I do wrong or how i can troubleshoot? I am missing a place where I can see fields for the coordinates - not sure though if they exist somewhere? How would the normal Workflow in the "Tools/Cartographies" Section be after selecting the location and seeing the Map?

Thanks for the great Software and for helping!

**Comment by akammerer** [comment]
Update: Is it normal that the glpi_plugin_positions_positions is completely empty? Not even colums? Did I mess up something on installing the plugin? 
MariaDB [glpi]> select * from glpi_plugin_positions_positions;
Empty set (0.000 sec)

**Comment by Marcigbe** [comment]
Hi akammrer,
I have the same problem, I have solved by modifying the glpi_plugin_positions_positions table the x_coordinates and y_coordinates fields. uncheck or remove unsigned parameter.

**Comment by Halfrust** [comment]
![errorsql](https://user-images.githubusercontent.com/119602696/205066374-8bbf5b81-8b3d-4f84-8df7-68783ccfc11b.PNG)

I can not see my computer on the map

**Comment by anywen** [comment]
Hello,
I'm on glpi 10.0.6 / Cartographie 6.0.2 and can confirm that the problem is still present.
Modifying the two columns x_coordinates and y_coordinates from int to double solved the problem too.

**Comment by tsmr** [comment]
Fixed in 6.0.3 version
